config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"

  # =========== USER ROUTES ===============
  resources :users
  # =========== BOOKINGS ROUTES ===============
  resources :bookings, except: [:new, :create] do
    member do
      patch :accept
      patch :decline
    end
  end
  # =========== WATCH ROUTES ===============
  resources :watches do
    resources :bookings, only: [:new, :create]
  end
  # =========== DASHBOARD ROUTES ===============
  get "/user/dashboard", to: "pages#dashboard"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :watch

  validates :starting_date, :ending_date, presence: true
  validate :ending_date_after_starting_date
  validates :status, inclusion: { in: ['Pending', 'Accepted', 'Declined'] }

  def ending_date_after_starting_date
    # vérifie si ending_date ou starting_date est vide => si true méthode se termine
    return if ending_date.blank? || starting_date.blank?

    if ending_date < starting_date
      errors.add(:ending_date, "must be after the starting date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :watches, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, :email, :password, presence: true
  validates :username, uniqueness: true
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :price, presence: true
  validates :brand, presence: true
  validates :model, presence: true
  validates :description, presence: true
  validates :movement_type, presence: true
  validates :movement_type, inclusion: { in: ["Manual", "Automatic"] }
  validates :gender, presence: true
  validates :gender, inclusion: { in: ["Woman", "Men", "Kid"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :accept, :decline]

  def index
    @bookings = Booking.all
  end

  def show
    # @booking est déjà défini grâce à set_booking
  end

  def new
    @booking = Booking.new
    @watch = Watch.find(params[:watch_id])
  end

  def create
    @watch = Watch.find(params[:watch_id])
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.watch = @watch
    @booking.user = @user
    @booking.status = "Pending"
    if @booking.save
      redirect_to watch_path(@watch), notice: '✅ Booking was successfully created.'
    else
      render :new, status: unprocessable_entity
    end
  end

  def edit
    # @booking est déjà défini grâce à set_booking
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  def accept
    @booking.update(status: 'Accepted')
    redirect_to bookings_url, notice: 'Booking was accepted.'
  end

  def decline
    @booking.update(status: 'Declined')
    redirect_to bookings_url, notice: 'Booking was declined.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:starting_date, :ending_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @current_user_bookings = current_user.bookings
    @current_user_watches = current_user.watches
    # @clients_bookings = Booking.find(:watch_id)
    # @current_user_rented_watches =
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # private
  # def user_params
  #   params.require(:user).permit(:username, :email, :password, :password_confirmation)
  # end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @watches = Watch.all
    @users = User.all
  end

  def new
    @watch = Watch.new
  end

  def create
    @watch = Watch.new(params_watch)
    @watch.user_id = current_user.id
    if @watch.save
      redirect_to @watch
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @watch = Watch.find(params[:id])
  end

  private

  def params_watch
    params.require(:watch).permit(:name, :price, :brand, :model, :description, :movement_type, :gender, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :watch_id %>
    <%= form.collection_select :watch_id, Watch.all, :id, :name, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :starting_date %>
    <%= form.date_field :starting_date %>
  </div>

  <div class="field">
    <%= form.label :ending_date %>
    <%= form.date_field :ending_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['Pending', 'Accepted', 'Declined'], include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Reservation</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back to Booking', @booking %> |
<%= link_to 'Back to List', bookings_path %>

app/views/bookings/index.html.erb
<h1>Liste des réservations</h1>

<%# <%= link_to 'Créer une nouvelle réservation', new_watch_booking_path, class: 'btn btn-primary' %> %>

<table class="table">
  <thead>
    <tr>
      <th>Date de début</th>
      <th>Date de fin</th>
      <th>Statut</th>
      <th>Montre</th>
      <th>Locataire</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.starting_date %></td>
        <td><%= booking.ending_date %></td>
        <td><%= booking.status %></td>
        <td><%= booking.watch.name %></td>
        <td><%= booking.user.username %></td>
        <td>
          <%= link_to 'Voir', booking, class: 'btn btn-info' %>
          <%= link_to 'Modifier', edit_booking_path(booking), class: 'btn btn-warning' %>
          <%= link_to booking_path(booking), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this reservation?" } do %>
            <div class="btn btn-danger">Supprimer </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<div class="reservation-form-container">
  <h1>Create your reservation for <strong><%= @watch.name %></strong></h1>
  <%= simple_form_for([@watch, @booking]) do |f| %>
    <%= f.input :starting_date, label: 'Starting Date' %>
    <%= f.input :ending_date, label: 'Ending Date' %>
    <%= f.submit 'Submit Reservation', class: 'btn-submit-reservation' %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Reservation Details</h1>
<p>
  <strong>Watch:</strong>
  <%= @booking.watch.name %>
</p>
<p>
  <strong>Renter:</strong>
  <%= @booking.user.username %>
</p>
<p>
  <strong>Starting Date:</strong>
  <%= @booking.starting_date %>
</p>
<p>
  <strong>Ending Date:</strong>
  <%= @booking.ending_date %>
</p>
<p>
  <strong>Status:</strong>
  <%= @booking.status %>
</p>
<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back to List', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacRent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="announcement-bar">
      Discover elegance on your wrist - Rent a luxury watch now!
    </div>
    <nav class="bg-black-navbar navbar navbar-expand-lg navbar-light bg-light">
      <div class="bg-black-navbar container-fluid">
        <!-- Liens en haut à gauche -->
        <%= link_to 'Offer Your Watch', new_watch_path, class: 'button-text-watches-index position-absolute top-0 start-0 ms-5 mt-2' %>
        <!-- Logo au centre -->
        <div class="mx-auto my-2">
          <%= link_to root_path do %>
            <%= image_tag('logo-final-tic-tac-rent.png', alt: 'Tic Tac Rent Logo', class: 'logo-container d-block mx-auto') %>
          <% end %>
          <!-- Liens en dessous du logo -->
          <div class="nav-link-container d-flex justify-content-center mt-2">
            <%= link_to 'Watches', watches_path, class: 'nav-link nav-link-style' %>
            <%= link_to 'Dashboard', user_dashboard_path, class: 'nav-link nav-link-style' %>
            <%= link_to 'Brands', "brands_path", class: 'nav-link nav-link-style' %>
          </div>
        </div>
        <!-- Liens en haut à droite -->
        <div class="d-flex justify-content-between nav-link position-absolute top-0 end-0 me-5 mt-2">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, turbo_method: :delete, class: 'nav-link nav-link-style' %>
          <% else %>
            <%= link_to 'Sign In', user_session_path, class: 'nav-link nav-link-style mr-5' %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link nav-link-style mr-5' %>
          <% end %>
        </div>
        <!-- Barre de recherche et panier en bas -->
        <div class="search-container position-absolute bottom-0 start-0 mb-3 ms-5">
          <%= form_with url: "search_path", method: :get, class: 'd-flex' do |form| %>
            <%= form.search_field :q, class: 'form-control me-2', placeholder: 'Recherche...' %>
            <%= form.submit 'Search', class: 'btn btn-outline-success' %>
          <% end %>
          <%= link_to "cart_path" do %>
            <i class="bi bi-cart3"></i>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- Pied de page -->
    <footer class="footer bg-dark text-light">
      <div class="container py-5">
        <div class="row">
          <!-- Colonne Newsletter -->
          <div class="col-md-3">
            <h5>Newsletter</h5>
            <p>Sign up now and get 10% off</p>
            <input type="email" class="form-control" placeholder="Your e-mail adress">
            <button type="submit" class="btn btn-primary mt-2">Suscribe</button>
          </div>
          <!-- Colonne Informations -->
          <div class="col-md-3">
            <h5>Informations</h5>
            <ul>
              <li>Tic Tac Rent</li>
              <li>Avenue des Champs-Élysées</li>
              <li>75 008 Paris</li>
              <li>+33 (0)5 62 68 55 39</li>
              <li>contact@tictacrent.com</li>
            </ul>
          </div>
          <!-- Colonne Nos engagements -->
          <div class="col-md-3">
            <h5>Our commitments</h5>
            <ul>
              <li>Delivery</li>
              <li>Secure payment</li>
              <li>Warranty - After-sales service</li>
              <li>Eco Tempo - Recycling</li>
              <li>Exchange or refund</li>
            </ul>
          </div>
          <!-- Colonne Notre société -->
          <div class="col-md-3">
            <h5>Our company</h5>
            <ul>
              <li>Legal notices</li>
              <li>CGV</li>
              <li>Privacy policy</li>
              <li>Personal data</li>
              <li>Contact us</li>
              <li>Terms and conditions of use - Rental</li>
            </ul>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col-12 text-center">
            <!-- Ici, placez vos icônes de réseaux sociaux -->
            <p>&copy; 2024 Tic Tac Rent</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container-dashboard" data-controller="toggle">
  <div class="row">
    <div class="sidebar col-4 justify-content-start">
      <div class="flex-shrink-0 p-3" style="width: 280px";>
        <a href="/" class="d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom">
          <svg class="bi pe-none me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-5 fw-semibold">DASHBOARD</span>
        </a>
        <ul class="list-unstyled ps-0">
          <li class="mb-1">
            <button class="btn btn-warning" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true" data-action="click->toggle#showContent">
              Your bookings
            </button>
            <div class="collapse show" id="home-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small d-none">
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">En cours</a>
                </li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Historique</a></li>
              </ul>
            </div>
          </li>
          <li class="mb-1">
            <button class="btn btn-warning" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false" data-action="click->toggle#showWatches">
              Your watches
            </button>
            <div class="collapse" id="dashboard-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small d-none" data-toggle-target="toggleUl">
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">En cours</a>
                </li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Historique</a></li>
              </ul>
            </div>
          </li>
          <li class="mb-1">
            <button class="btn btn-warning" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
              Requests
            </button>
            <div class="collapse" id="orders-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Inutile 2</a></li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Inutile 2</a></li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Inutile 3</a></li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Inutile 4</a></li>
              </ul>
            </div>
          </li>
          <%# <li class="border-top my-3"></li> %>
          <li class="mb-1">
            <button class="btn btn-warning" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
              Settings
            </button>
            <div class="collapse" id="account-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">...</a></li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">...</a></li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">...</a></li>
                <li><a href="#" class="link-body-emphasis d-inline-flex text-decoration-none rounded">...</a></li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="bookings-dashboard col-8 justify-content-center d-none" data-toggle-target="togglableElement">
      <% @current_user_bookings.each do |booking| %>
        <div class= "booking-dashboard-infos">
          <p><strong>Montre</strong>: <%= booking.watch.name %></p>
          <p><strong>Du</strong>: <%= booking.starting_date %></p>
          <p><strong>Au</strong>: <%= booking.ending_date %></p>
          <p><strong>Total</strong>: <%= (booking.ending_date - booking.starting_date) * booking.watch.price %> $ </p>
        </div>
      <% end %>
    </div>
    <div class="watches-dashboard col-8 justify-content-center d-none" data-toggle-target="togglableWatches">
      <p>Mes montres</p>
      <ul>
        <% @current_user_watches.each do |watch| %>
          <li>
            <div class= "watch">
              <p>Montre: <%= watch.name %></p>
              <p>rent periods: <%=  %></p>
            </div>
            <ul>
              <% if watch.bookings == [] %>
                <p><strong>No reservation for this watch 😿</strong></p>
              <% else %>
                <% watch.bookings.each do |booking|%>
                  <li>
                    <p><%= booking.user.username %></p>
                  </li>
                <% end %>
              </ul>
              <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="requests">
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <!-- Contenu principal -->
  <div class="banner-image">
    <div class="container-bannner text-center">
      <div class="image-text">
        <h2>Discover Luxury Experience with Tic Tac Rent</h2>
        <p>At Tic Tac Rent, we believe luxury should be accessible to everyone, anytime. Founded by three young visionaries, our company is on a mission to reinvent how you perceive and enjoy luxury watches.</p>
        <h2>Luxury on Demand</h2>
        <p>Imagine having access to an exclusive collection of luxury watches, right at your fingertips, without the need for a long-term commitment. With Tic Tac Rent, it's now possible. Our platform gives you the freedom to rent renowned watches for special occasions or simply to elevate your everyday style.</p>
        <%= link_to 'Discover', "#", class: "btn-home-page btn btn-primary mt-3" %>
      </div>
  </div>
</div>

<!-- Contenu How it works -->
<div class="how-it-works-section">
  <h2 class="works-text text-center">How it Works?</h2>

  <div class="container-home-page">
    <div class="card-deck">
      <div class="card card-home-page">
        <div class="card-image-placeholder-one"></div>
        <div class="card-body card-body-home-page">
          <h3>Explore our Collection</h3>
          <p>Browse through our wide range of luxury watches available for rent. Discover prestigious brands and iconic models tailored to your style and needs.</p>
          <%= link_to 'Our collection', "explore_path", class: "btn-cards btn btn-primary" %>
        </div>
      </div>

      <div class="card card-home-page">
        <div class="card-image-placeholder-two"></div>
        <div class="card-body card-body-home-page">
          <h3>Book your Watch</h3>
          <p>Select the watch of your dreams from our diverse collection. Check availability and pricing details, then book your watch in just a few clicks. We'll confirm your booking and connect you with the owner to arrange pickup.</p>
          <%= link_to 'Reserve', "book_path", class: "btn-cards btn btn-primary" %>
        </div>
      </div>

      <div class="card card-home-page">
        <div class="card-image-placeholder-three"></div>
        <div class="card-body card-body-home-page">
          <h3>Enjoy your Watch</h3>
          <p>Once your booking is confirmed, head to the owner's location to pick up your watch. Wear it with elegance and at the end of the rental period, simply return the watch to the owner as per the agreed-upon instructions during booking.</p>
          <%= link_to 'Assure', "enjoy_path", class: "btn-cards btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/watches/index.html.erb
<div class="black-linear-bg black-linear-bg-watches-index">
  <div class="container">
    <div class="banner">
      <h1>List of all the Watches:</h1>
    </div>
    <div class="text-center mt-4">
      <%= link_to new_watch_path(@watch), data: { turbo_confirm: "If you are not logged in, you'll be redirected to the login page" }, class: "btn btn rounded-pill" do %>
        <div class="button-text-watches-index">You too post your watch</div>
      <% end %>
    </div>
    <div class="mt-4"></div>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
      <% @watches.each do |watch| %>
        <% watch_owner = @users.find(watch.user_id) %>
        <div class="col mb-4">
          <%= link_to watch_path(watch), class: "text-decoration-none" do %>
            <div class="card card-watches-index h-100 border-0 rounded-lg shadow">
              <% if watch.photo.attached? %>
                <%= cl_image_tag watch.photo.key, class:"card-img-top-watches-index rounded-3" %>
              <% else %>
                <img src="<%= watch.image_url %>" class="card-img-top-watches-index rounded-3">
              <% end %>
              <div class="card-body card-body-watches-index">
                <h5 class="card-title card-title-watches-index text-center mb-2"><%= watch.name %></h5>
                <hr class="my-1">
                <p class="card-text mb-1"><%= watch.description %></p>
                <hr class="my-1">
                <div class="d-flex justify-content-between">
                  <p class="card-text"><small class="text-muted">Posted by <%= watch_owner.username %></small></p>
                  <p class="price-watches-index"><%= watch.price %> $ / day</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/watches/new.html.erb
<div class="container-watches-new">
  <div class="card-watches-new">
    <h1>Post your Watch :</h1>
    <%= simple_form_for(@watch) do |f| %>
      <%= f.input :name, class: "input-watches-new" %>
      <%= f.input :price, class: "input-watches-new" %>
      <%= f.input :brand, class: "input-watches-new" %>
      <%= f.input :model, class: "input-watches-new" %>
      <%= f.input :description, class: "input-watches-new" %>
      <%= f.input :movement_type, as: :select, collection: ["Manual", "Automatic"], class: "input-watches-new"  %>
      <%= f.input :gender, as: :select, collection: ["Woman", "Men", "Kid"], class: "input-watches-new" %>
      <%= f.input :photo, as: :file, class: "input-watches-new" %>
      <%= f.submit "Submit", class: "btn-watches-new" %>
    <% end %>
    <div class="back-link-watches-new"><%= link_to "<- Back", watches_path, class: "btn-watches-new" %> </div>
  </div>
</div>

app/views/watches/show.html.erb
<div class="banner-show-watch">
  <div class="container">
    <h1><%= @watch.brand %></h1>
    <h2><%= @watch.name %></h2>
    <h3><%= @watch.movement_type %></h3>
  </div>
</div>
<div class="watch-details-container">
  <div class="container-show-watch container">
    <div class="watch-show-image">
      <% if @watch.photo.attached? %>
        <%= cl_image_tag @watch.photo.key, class:"card-img-top rounded-3" %>
      <% else %>
        <img src="<%= @watch.image_url %>" class="card-img-top rounded-3">
      <% end %>
    </div>
    <div class="watch-show-info">
      <h3>Watch Model :</h3>
      <p><%= @watch.model %></p>
      <h3>Description :</h3>
      <p><%= @watch.description %></p>
      <h3>Gender :</h3>
      <p><%= @watch.gender %></p>
      <div class= price-show-watch>
        <p><%= @watch.price %>$ / day </p>
      </div>
      <div class="actions-show-watch container">
        <div>
          <%= link_to "Book this watch", new_watch_booking_path(@watch), class: "btn-show-watch-one btn btn-primary" %>
        </div>
        <div>
          <%= link_to "<- Back", watches_path, class: "btn-show-watch-two btn btn-secondary" %>
        </div>
      </div>
      <div class="payment-security">
    <i class="fas fa-shield-alt"></i> Payment secured
  </div>
    </div>
  </div>
</div>